
location ^~ /oauth2/ { proxy_pass http://127.0.0.1:4182; proxy_set_header Host $host; }
location = /oauth2/auth { internal; proxy_pass http://127.0.0.1:4182/oauth2/auth; proxy_pass_request_body off; }
location @login { return 302 https://ha.niubia.top/oauth2/sign = login?rd=$request_uri; }
